os: linux
dist: bionic
language: python

services:
  - docker

jobs:
  include:
    - name: "Generate SBOM"
      os: linux
      dist: focal # Overrides global dist
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_format: cyclonedx-json
          input_dir: '/python'
          output_dir: '/sbom/python'
      script:
        - echo "Generating SBOM"
        - sudo mkdir -p /sbom/python # Ensure output directory exists
        - pip install -r requirements.txt # Install dependencies first
        - python hello_world.py

before_install:
  - rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem uninstall -aIx dpl
  - rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl -v 2.0.3.beta.4

after_success:
  - echo "Build succeeded"
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python

after_failure:
  - echo "Build failed"
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python
