os: linux
dist: bionic
language: python

services:
  - docker

jobs:
  include:
    - name: "Generate SBOM"
      os: linux
      dist: focal
      script:
        - echo "Generating SBOM"
        - sudo mkdir -p /sbom/python
        - pip install -r requirements.txt
        - python hello_world.py

deploy:
  provider: script
  script: echo "Generating SBOM for deployment"
  on:
    branch: main

before_install:
  - rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem uninstall -aIx dpl
  - rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl -v 2.0.3.beta.4

after_success:
  - echo "Build succeeded"
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python

after_failure:
  - echo "Build failed"
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python
